### ISSUE TITLE
Integrate co-optimus.com's multiplayer information

### ISSUE THREAD

**Issue by andrasfuchs** [Nebukam/steam-game-finder#2]
A site called [co-optimus.com](https://www.co-optimus.com) collects multiplayer information of games. It is particularly useful when more than 4 people planning to play together, because there are not many games that support that many co-op players.

I talked to the owners of the site, and asked them for API access in the hope of integrating it into this Steam Game Finder extension. 

They made it available, so for example if we are interested in the Steam game with the application id of `359550`, we can call http://api.co-optimus.com/games.php?search=true&steam=359550 and get back a game object.

![image](https://user-images.githubusercontent.com/910321/146678919-0bae6df9-4c97-4b07-856b-9f267a082f82.png)

This `game` object has an `online` property that indicates the maximum number of people who can play together with that particular game.

Would it be possible to show this information on the cards of the games in the extension, or even filter the results to those support at least x players?

**Comment by Nebukam** [comment]
Hey @andrasfuchs, that would be definitely be a good addition, however I'd be interested to see how they accessed the "max number of player" infos.
Currently I maintain my own database of steam title on github (in the private repo used for github pages) to make sure I limit the number of API requests per title loaded and don't rely on any third parties other than Steam itself for the app to run. 

I'll look into adding this info to my own db, rather than relying on an additional resource call to be able to run the filters on the gamelist 👍

**Comment by andrasfuchs** [comment]
I think co-optimus maintains its own database, and they upload the max co-op player info manually, but I might be wrong.

I also checked the Steam tags on https://steamdb.info/tags/, but I can see only one that indicates maximum player count ([4 Player Local](https://steamdb.info/tag/4840/)). Ideally we would have tags like "4 Player Online Co-Op" or "5 Player Online Co-Op", but I don't think they are used.

Anyway, it would be great if you could integrate the information from co-optimus, even if only for the most popular titles.

**Comment by Nebukam** [comment]
Ok so I started looking at cooptimus data and updating my own db model fetching their info (needless to say some credit will be due there). There is 2277 games with multiplayer infos out of ~190.000 steam entries (number includes soundtracks movie and a bunch of other irrelevant stuffs); so that's a small yet meaningful overlap.

There will be some additional UI dev required to support some more interesting types of filters but it will definitely make it into the next release -- soon™ 👍

**Comment by andrasfuchs** [comment]
That's excellent, thank you!!

**Comment by Nebukam** [comment]
I'm still working on updating the app/extension, meanwhile I'm done dumping the steam DB & combining it with cooptimus data, if you're curious : https://github.com/Nebukam/steam-db
(it's not availble through github pages at the time of writing but should be in the next few hours)

**Comment by andrasfuchs** [comment]
Great stuff, and thank you for the shout-out!
I can't wait to see it in the extension and try it with my gaming buddies 🚀

**Comment by Nebukam** [comment]
Done! ^_^
While the extension is under review I udpated the [readme](https://github.com/Nebukam/steam-game-finder) of the git to include a link to the [webapp version of the app](https://nebukam.github.io/steam-game-finder/pwa/).

**Comment by andrasfuchs** [comment]
Awesome!! 😍
